bundler_cache:
  image: alpine:3.1
  command: echo
  volumes:
    - /bundler_cache

web:
  image: donate/latest
  command: rails server --port 3000 --binding 0.0.0.0
  ports:
    - "3000:3000"
  volumes:
    - ".:/srv/donate.noisebridge.net"
  volumes_from: 
    - bundler_cache
    
